---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  name: "ghost"
  labels:
    nirmata.io/service.name: "ghost"
    nirmata.io/application.name: "ghost"
    nirmata.io/component: "ghost"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    nirmata.io/application.name: "ghost"
    nirmata.io/component: "ghost"
  ports:
  - name: "http"
    port: 2368
    protocol: "TCP"

---
kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  annotations: {}
  name: "ghost"
  labels:
    nirmata.io/deployment.name: "ghost"
    nirmata.io/service.name: "ghost"
    nirmata.io/user.email: "mohan-anzentechnology-com"
    nirmata.io/application.name: "ghost"
    nirmata.io/component: "ghost"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/application.name: "ghost"
      nirmata.io/component: "ghost"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "ghost"
        test: "test123"
        nirmata.io/service.name: "ghost"
        nirmata.io/user.email: "mohan-anzentechnology-com"
        nirmata.io/application.name: "ghost"
        nirmata.io/component: "ghost"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "ghost"
        image: "ghost:0.11.13-alpine"
        command: []
        args: []
        ports:
        - name: "http"
          containerPort: 2368
          protocol: "TCP"

---
kind: "NetworkPolicy"
apiVersion: "extensions/v1beta1"
spec:
  podSelector:
    matchLabels:
      nirmata.io/application.name: "ghost"
      nirmata.io/component: "ghost"
    matchExpressions: []
  policyTypes:
  - "Ingress"
  - "Egress"
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          nirmata.io/application.name: "ghost2"
        matchExpressions: []
  egress:
  - {}
metadata:
  annotations: {}
  name: "ghost"
  labels:
    nirmata.io/networkpolicy.name: "ghost"
    nirmata.io/application.name: "ghost"
    nirmata.io/component: "ghost"

---
kind: "NetworkPolicy"
apiVersion: "extensions/v1beta1"
spec:
  podSelector:
    matchLabels: {}
    matchExpressions: []
  policyTypes:
  - "Ingress"
  - "Egress"
metadata:
  annotations: {}
  name: "ghost-default"
  labels:
    nirmata.io/networkpolicy.name: "ghost-default"
    nirmata.io/application.name: "ghost"
