---
apiVersion: "v1"
kind: "Service"
metadata:
 annotations: {}
 name: "hello-world"
 labels:
   nirmata.io/service.name: "hello-world"
   nirmata.io/application.name: "api-application-test"
   nirmata.io/component: "hello-world"
spec:
 externalIPs: []
 loadBalancerSourceRanges: []
 type: "ClusterIP"
 selector:
   nirmata.io/application.name: "api-application-test"
   nirmata.io/component: "hello-world"
 ports:
 - name: "http"
   port: 8080
   protocol: "TCP"

---
kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
 annotations: {}
 name: "hello-world"
 labels:
   nirmata.io/deployment.name: "hello-world"
   nirmata.io/application.run: "hello-world"
   nirmata.io/environment.name: "qa-10apr"
   nirmata.io/service.name: "hello-world"
   nirmata.io/user.email: "mohan-anzentechnology-com"
   nirmata.io/application.name: "api-application-test"
   nirmata.io/component: "hello-world"
spec:
 replicas: 3
 revisionHistoryLimit: 5
 selector:
   matchLabels:
     nirmata.io/service.name: "hello-world"
     nirmata.io/application.name: "api-application-test"
     nirmata.io/component: "hello-world"
   matchExpressions: []
 strategy:
   type: "RollingUpdate"
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
 template:
   metadata:
     annotations: {}
     labels:
       nirmata.io/deployment.name: "hello-world"
       nirmata.io/application.run: "hello-world"
       nirmata.io/environment.name: "qa-10apr"
       nirmata.io/service.name: "hello-world"
       nirmata.io/user.email: "mohan-anzentechnology-com"
       nirmata.io/application.name: "api-application-test"
       nirmata.io/component: "hello-world"
   spec:
     terminationGracePeriodSeconds: 30
     nodeSelector: {}
     containers:
     - name: "hello-world"
       image: "nirmata/hello-world:green"
       command: []
       args: []
       ports:
       - name: "http"
         containerPort: 8080
         protocol: "TCP"